/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3493dbbb-8b3f-45f2-9547-e257ab8dd6df",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Ig4M2YLXD",
    "aws_user_pools_web_client_id": "6pi3nnhm80cvqkcnb2ic1nb3i0",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "apid2e585c8",
            "endpoint": "https://wc38vt2yj0.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
